name: ie-bank-infra
on:
  workflow_dispatch:  # This allows manual triggering
  push:
    branches:
      - '*'  # This will run on any branch
    paths:
      - 'infra/**'
      - '!infra/scripts/**'
  pull_request:
    branches:
      - main  # This will run on pull requests to main
    paths:
      - 'infra/**'
      - '!infra/scripts/**'

env:
  RESOURCE_GROUP_DEV: BCSAI2024-DEVOPS-STUDENTS-B-DEV
  RESOURCE_GROUP_UAT: BCSAI2024-DEVOPS-STUDENTS-B-UAT
  SUBSCRIPTION_ID_DEV: e0b9cada-61bc-4b5a-bd7a-52c606726b3b
  USER_ALIAS: dkumlin

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Bicep linter
        run: az bicep build --file ./infra/main.bicep

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    environment: Development

    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Debug
        run: |
          echo "ENV: ${{ vars.ENV }}"
          echo "DBHOST: ${{ vars.DBHOST }}"
          echo "DBNAME: ${{ vars.DBNAME }}"
          echo "FLASK_APP: ${{ vars.FLASK_APP }}"
          echo "FLASK_DEBUG: ${{ vars.FLASK_DEBUG }}"
      - name: Deploy to Development
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ env.SUBSCRIPTION_ID_DEV }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_DEV }}
          template: ./infra/main.bicep
          parameters: >
            ./infra/parameters/dev.parameters.json 
            branch=${{ github.ref_name }}
            repositoryUrl=https://github.com/bigdawgbank/ie-bank 
            appServiceAPIEnvVarENV=${{ vars.ENV }} 
            appServiceAPIEnvVarDBHOST=${{ vars.DBHOST }} 
            appServiceAPIEnvVarDBNAME=${{ vars.DBNAME }} 
            appServiceAPIEnvVarDBPASS=${{ secrets.DBPASS }} 
            appServiceAPIDBHostDBUSER=${{ secrets.DBUSER }} 
            appServiceAPIDBHostFLASK_APP=${{ vars.FLASK_APP }} 
            appServiceAPIDBHostFLASK_DEBUG=${{ vars.FLASK_DEBUG }}
          deploymentName: ${{ env.USER_ALIAS }}-dev

  deploy-uat:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'pull_request' && github.base_ref == 'main' || github.ref == 'refs/heads/main'
    environment: UAT

    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Debug
        run: |
          echo "ENV: ${{ vars.ENV }}"
          echo "DBHOST: ${{ vars.DBHOST }}"
          echo "DBNAME: ${{ vars.DBNAME }}"
          echo "FLASK_APP: ${{ vars.FLASK_APP }}"
          echo "FLASK_DEBUG: ${{ vars.FLASK_DEBUG }}"
      - name: Deploy to UAT
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ env.SUBSCRIPTION_ID_DEV }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_UAT }}
          template: ./infra/main.bicep
          parameters: >
            ./infra/parameters/uat.parameters.json
            repositoryUrl=https://github.com/bigdawgbank/ie-bank 
            branch=${{ github.ref_name }} 
            appServiceAPIEnvVarENV=${{ vars.ENV}} 
            appServiceAPIEnvVarDBHOST=${{ vars.DBHOST }} 
            appServiceAPIEnvVarDBNAME=${{ vars.DBNAME }} 
            appServiceAPIEnvVarDBPASS=${{ secrets.DBPASS }} 
            appServiceAPIDBHostDBUSER=${{ secrets.DBUSER }} 
            appServiceAPIDBHostFLASK_APP=${{ vars.FLASK_APP }} 
            appServiceAPIDBHostFLASK_DEBUG=${{ vars.FLASK_DEBUG }}
          deploymentName: ${{ env.USER_ALIAS }}-uat
