name: ie-bank-infra

on:
  workflow_dispatch:  # Allows manual triggering
  push:
    branches:
      - '*'  # Runs on any branch
    paths:
      - 'infra/**'
      - '!infra/scripts/**'
  pull_request:
    branches:
      - main  # Runs on pull requests to main
    paths:
      - 'infra/**'
      - '!infra/scripts/**'

env:
  RESOURCE_GROUP_DEV: BCSAI2024-DEVOPS-STUDENTS-B-DEV
  RESOURCE_GROUP_UAT: BCSAI2024-DEVOPS-STUDENTS-B-UAT
  SUBSCRIPTION_ID_DEV: e0b9cada-61bc-4b5a-bd7a-52c606726b3b
  USER_ALIAS: dkumlin
  LOCATION: northeurope  # Ensure this is set to a valid Azure location

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Bicep linter
        run: az bicep build --file ./infra/main.bicep

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    environment: Development
    env:
      ENV: dev
      DBHOST: dkumlin-dbsrv-dev.postgres.database.azure.com
      DBNAME: dkumlin-db-dev
      FLASK_APP: iebank_be
      FLASK_DEBUG: True
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Debug
        run: |
          echo "ENV: ${{ env.ENV }}"
          echo "DBHOST: ${{ env.DBHOST }}"
          echo "DBNAME: ${{ env.DBNAME }}"
          echo "FLASK_APP: ${{ env.FLASK_APP }}"
          echo "FLASK_DEBUG: ${{ env.FLASK_DEBUG }}"
      - name: Deploy Infrastructure to Development
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ env.SUBSCRIPTION_ID_DEV }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_DEV }}
          template: ./infra/main.bicep
          parameters: |
            ./infra/parameters/dev.parameters.json
            branch=${{ github.ref_name }}
            repositoryUrl=https://github.com/bigdawgbank/ie-bank
            appServiceAPIEnvVarENV=${{ env.ENV }}
            appServiceAPIEnvVarDBHOST=${{ env.DBHOST }}
            appServiceAPIEnvVarDBNAME=${{ env.DBNAME }}
            appServiceAPIEnvVarDBPASS=${{ secrets.DBPASS }}
            appServiceAPIDBHostDBUSER=${{ secrets.DBUSER }}
            appServiceAPIDBHostFLASK_APP=${{ env.FLASK_APP }}
            appServiceAPIDBHostFLASK_DEBUG=${{ env.FLASK_DEBUG }}
            workbookDisplayName=WorkbookLarbi
          deploymentName: ${{ env.USER_ALIAS }}-dev

      - name: Deploy Workbook to Development
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ env.SUBSCRIPTION_ID_DEV }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_DEV }}
          template: ./workbooks/workbook.bicep
          parameters: |
            logAnalyticsWorkspaceName=dkumlin-logAnalyticsWorkspace-dev
            location=${{ env.LOCATION }}
            workbookDisplayName=WorkbookLarbi
          deploymentName: ${{ env.USER_ALIAS }}-workbook-dev

  deploy-uat:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'pull_request' && github.base_ref == 'main' || github.ref == 'refs/heads/main'
    environment: UAT
    env:
      ENV: uat
      DBHOST: dkumlin-dbsrv-uat.postgres.database.azure.com
      DBNAME: dkumlin-db-uat
      FLASK_APP: iebank_be
      FLASK_DEBUG: False
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Debug
        run: |
          echo "ENV: ${{ env.ENV }}"
          echo "DBHOST: ${{ env.DBHOST }}"
          echo "DBNAME: ${{ env.DBNAME }}"
          echo "FLASK_APP: ${{ env.FLASK_APP }}"
          echo "FLASK_DEBUG: ${{ env.FLASK_DEBUG }}"
      - name: Deploy Infrastructure to UAT
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ env.SUBSCRIPTION_ID_DEV }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_UAT }}
          template: ./infra/main.bicep
          parameters: |
            ./infra/parameters/uat.parameters.json
            branch=${{ github.ref_name }}
            repositoryUrl=https://github.com/bigdawgbank/ie-bank
            appServiceAPIEnvVarENV=${{ env.ENV }}
            appServiceAPIEnvVarDBHOST=${{ env.DBHOST }}
            appServiceAPIEnvVarDBNAME=${{ env.DBNAME }}
            appServiceAPIEnvVarDBPASS=${{ secrets.DBPASS }}
            appServiceAPIDBHostDBUSER=${{ secrets.DBUSER }}
            appServiceAPIDBHostFLASK_APP=${{ env.FLASK_APP }}
            appServiceAPIDBHostFLASK_DEBUG=${{ env.FLASK_DEBUG }}
            workbookDisplayName=WorkbookLarbi
          deploymentName: ${{ env.USER_ALIAS }}-uat

      - name: Deploy Workbook to UAT
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ env.SUBSCRIPTION_ID_DEV }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_UAT }}
          template: ./workbooks/workbook.bicep
          parameters: |
            logAnalyticsWorkspaceName=dkumlin-logAnalyticsWorkspace-uat
            location=${{ env.LOCATION }}
            workbookDisplayName=WorkbookLarbi
          deploymentName: ${{ env.USER_ALIAS }}-workbook-uat
