name: ie-bank-infra
on:
  workflow_dispatch:  # This allows manual triggering
  push:
    branches:
      - '*'  # This will run on any branch
    paths:
      - 'infra/**'
      - '!infra/scripts/**'
  pull_request:
    branches:
      - main  # This will run on pull requests to main
    paths:
      - 'infra/**'
      - '!infra/scripts/**'

env:
  RESOURCE_GROUP_DEV: BCSAI2024-DEVOPS-STUDENTS-B-DEV
  RESOURCE_GROUP_UAT: BCSAI2024-DEVOPS-STUDENTS-B-UAT
  RESOURCE_GROUP_PROD: BCSAI2024-DEVOPS-STUDENTS-B-PROD
  SUBSCRIPTION_ID: e0b9cada-61bc-4b5a-bd7a-52c606726b3b
  USER_ALIAS: dkumlin

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Install Bicep CLI
      - name: Install Bicep CLI
        run: |
          echo "Installing Bicep CLI..."
          az bicep install
        
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      #- name: Validate Bicep deployment
        #run: |
            #echo "Validating Bicep deployment..."
            #for file in $(find ./infra -name '*.bicep'); do
                    #az deployment group what-if \
                    #--resource-group $RESOURCE_GROUP_DEV \
                    #--template-file $file \
                    #--parameters @./infra/parameters/dev.parameters.json || exit 1
            #done
            #echo "Deployment validation completed successfully!"
        
        
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bicep

      - name: Validate Bicep deployment
        run: |
            echo "Validating Bicep deployment..."
            for file in $(find ./infra -name '*.bicep'); do
                    az deployment group what-if \
                    --resource-group $RESOURCE_GROUP_DEV \
                    --template-file $file \
                    --parameters @./infra/parameters/dev.parameters.json || exit 1
            done
            echo "Deployment validation completed successfully!"
      - name: Run Unit Tests with arm-ttk
        run: |
            echo "Cloning arm-ttk for unit testing..."
            git clone https://github.com/Azure/arm-ttk.git
            echo "Running arm-ttk tests..."
            pwsh ./arm-ttk/arm-ttk.ps1 ./infra/**/*.bicep || exit 1
  deploy-dev:
    runs-on: ubuntu-latest
    needs: test
    environment: Development

    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Debug
        run: |
          echo "ENV: ${{ vars.ENV }}"
          echo "DBHOST: ${{ vars.DBHOST }}"
          echo "DBNAME: ${{ vars.DBNAME }}"
          echo "FLASK_APP: ${{ vars.FLASK_APP }}"
          echo "FLASK_DEBUG: ${{ vars.FLASK_DEBUG }}"
      - name: Deploy to Development
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ env.SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_DEV }}
          template: ./infra/main.bicep
          parameters: >
            ./infra/parameters/dev.parameters.json 
            appServiceAPIEnvVarENV=${{ vars.ENV }} 
            appServiceAPIEnvVarDBHOST=${{ vars.DBHOST }} 
            appServiceAPIEnvVarDBNAME=${{ vars.DBNAME }} 
            appServiceAPIEnvVarDBPASS=${{ secrets.DBPASS }} 
            appServiceAPIDBHostDBUSER=${{ secrets.DBUSER }} 
            appServiceAPIDBHostFLASK_APP=${{ vars.FLASK_APP }} 
            appServiceAPIDBHostFLASK_DEBUG=${{ vars.FLASK_DEBUG }}
          deploymentName: ${{ env.USER_ALIAS }}-dev

  deploy-uat:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'pull_request' && github.base_ref == 'main' || github.ref == 'refs/heads/main'
    environment: UAT

    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Debug
        run: |
          echo "ENV: ${{ vars.ENV }}"
          echo "DBHOST: ${{ vars.DBHOST }}"
          echo "DBNAME: ${{ vars.DBNAME }}"
          echo "FLASK_APP: ${{ vars.FLASK_APP }}"
          echo "FLASK_DEBUG: ${{ vars.FLASK_DEBUG }}"
      - name: Deploy to UAT
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ env.SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_UAT }}
          template: ./infra/main.bicep
          parameters: >
            ./infra/parameters/uat.parameters.json 
            appServiceAPIEnvVarENV=${{ vars.ENV }} 
            appServiceAPIEnvVarDBHOST=${{ vars.DBHOST }} 
            appServiceAPIEnvVarDBNAME=${{ vars.DBNAME }} 
            appServiceAPIEnvVarDBPASS=${{ secrets.DBPASS }} 
            appServiceAPIDBHostDBUSER=${{ secrets.DBUSER }} 
            appServiceAPIDBHostFLASK_APP=${{ vars.FLASK_APP }} 
            appServiceAPIDBHostFLASK_DEBUG=${{ vars.FLASK_DEBUG }}
          deploymentName: ${{ env.USER_ALIAS }}-uat

  deploy-prod:
    runs-on: ubuntu-latest
    needs: test
    environment: PROD

    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Debug
        run: |
          echo "ENV: ${{ vars.ENV }}"
          echo "DBHOST: ${{ vars.DBHOST }}"
          echo "DBNAME: ${{ vars.DBNAME }}"
          echo "FLASK_APP: ${{ vars.FLASK_APP }}"
          echo "FLASK_DEBUG: ${{ vars.FLASK_DEBUG }}"
      - name: Deploy to Production
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ env.SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_PROD }}
          template: ./infra/main.bicep
          parameters: >
            ./infra/parameters/prod.parameters.json 
            appServiceAPIEnvVarENV=${{ vars.ENV }} 
            appServiceAPIEnvVarDBHOST=${{ vars.DBHOST }} 
            appServiceAPIEnvVarDBNAME=${{ vars.DBNAME }} 
            appServiceAPIEnvVarDBPASS=${{ secrets.DBPASS }} 
            appServiceAPIDBHostDBUSER=${{ secrets.DBUSER }} 
            appServiceAPIDBHostFLASK_APP=${{ vars.FLASK_APP }} 
            appServiceAPIDBHostFLASK_DEBUG=${{ vars.FLASK_DEBUG }}
          deploymentName: ${{ env.USER_ALIAS }}-prod